(lang dune 3.12)

(name day05)

(generate_opam_files true)

(package
 (name day05)
 (depends ocaml dune))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/dune-files.html#dune-project
